### ISSUE TITLE
Unable to get same build files

### ISSUE THREAD

**Issue by vivi-gomez** [ujw0l/masonry-gallery#14]
I tried your repository, but I am unable to get the same files in /build as those you provide.
I wonder if files in src or package.json are the necessary ones to do npm build and get the same ones as yours.

Likewise, I would like to try to add breakpoints for different screen size (mobile, tablet, desktop)

Thank you. Nice plugin

**Comment by ujw0l** [comment]
Hello

Most probably problem is I modified js-masonry package to be imported as module , you need to find this particular node module and add "export" in front of class so it can be exported as module thats it , same thing with ctc-gallery-viewer package. I created it as to be used as class , just modified it to work as module for this project.

Thanks for liking my plugin. If it is possible,  please consider rating my plugin in wordpress.org [link](https://wordpress.org/support/plugin/block-for-masonry-gallery/reviews/#new-post) , I know it is not much, but will encourage me on keep working on it

Thanks and have a wonderful day

**Comment by ujw0l** [comment]
let  me know,if you need any help.
